### ISSUE TITLE
Positive/Negative Lookbehind not supported?

### ISSUE THREAD

**Issue by rabeet** [humio/jitrex#7]
```java
String jvmRegex = "(?<=a)";
com.humio.jitrex.Pattern jitrexPattern = com.humio.jitrex.Pattern.compile(jvmRegex);
```
Exception in thread "main" com.humio.util.jint.util.CompilerException: CompilerError[4804]
	at com.humio.jitrex.parser.RParser.parseImpl(RParser.java:277)
	at com.humio.jitrex.parser.RParser.parse(RParser.java:82)
	at com.humio.jitrex.parser.RParser.parse(RParser.java:72)
	at com.humio.jitrex.Pattern.compile(Pattern.java:158)
	at com.humio.jitrex.Pattern.compile(Pattern.java:147)

**Comment by 4ntoine** [comment]
+1

**Comment by bjb298** [comment]
Any progress on this?

**Comment by mhensler** [comment]
[https://github.com/humio/jitrex/blob/master/README.md](url) mentions:
> Removed some Perl-style regex features like < and >
